spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_lms
    username: Ratana123
    password: Ratana123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true