spring:
  datasource:
    url: jdbc:postgresql://dpg-cq8tds5ds78s7395ku10-a:5432/db_lms
    username: db_lms_user
    password: PYPM9TZCexVmt04vysQlhTo3p2zbuY6N
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false